### ISSUE TITLE
DemoTools not installing on R version 4.0.3 (2020-10-10) 

### ISSUE THREAD

**Issue by RamdaneOS** [timriffe/DemoTools#154]
Hi, 
I am trying to install the DemoTools package and it seems that there is a version issue. Here is the error message : 

Error: Failed to install 'DemoTools' from GitHub:
  Failed to install 'fertestr' from GitHub:
  (converted from warning) package ‘ungroup’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by timriffe** [comment]
Thanks for reporting!

This was a bit of a rabbit hole, but here's my current interpretation. 

# Why it's currently not installing:
`DemoTools` depends on `ungroup`. And it also depends on `fertestr`, which depends on `ungroup`. `ungroup` is down from CRAN because its dependency `MortalitySmooth` is down, because its dependency `svcm` is down. And it didn't trace it farther from that. I've emailed the maintainers of `svcm`, `MortalitySmooth`, and `ungroup` with a potential solution. Until that dependency chain is properly revived, you can get things installed like so:

```
# archived versions of svcm and MortalitySmooth
install.packages("https://cran.r-project.org/src/contrib/Archive/svcm/svcm_0.1.2.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/MortalitySmooth/MortalitySmooth_2.3.4.tar.gz", repos = NULL, type = "source")

# Maybe also other ungroup deps:
install.packages("Rcpp")
install.packages("rgl") # this might need installation of an external dependency
install.packages("RcppEigen") 

# then:
remotes::install_github("mpascariu/ungroup")

# and finally DemoTools:
remotes::install_github("timriffe/DemoTools")
```

There's a way for me to get all this to work automatically on install, but I need nods from the maintainers of those other packages first.

**Comment by RamdaneOS** [comment]
Thank you for your help.
The temporary solution worked on macOS High Sierra. I had an error installing `ungroup' but I was able to fix this after installing XQuartz. Looking forward to the final solution.
Thanks.

**Comment by cimentadaj** [comment]
This is fixed right @timriffe ?
