### ISSUE TITLE
Some examples with issues

### ISSUE THREAD

**Issue by jmaburto** [timriffe/DemoTools#34]
##MAV.R
##mav  Added graph. Tim, in the example chcek the NA's

##nAx.R
##axPAS Added example, but is the functions is returnings NA's. Tim, please check.
##ax.greville.mortpak Added example, but not working. Tim, please check.
##SPENCER.R
##spencer Added example and graph but NA's prodcued in a lot of ages. Tim, please check.

**Comment by timriffe** [comment]
`MAV()` `NA`'s in example are as expected. This is because `n = 3` gives a centered moving average, so the endpoints are left out (nothing to left of age 0 and nothing to right of highest non-open age). The open age gets an `NA` too before other calcs because it won't faithfully average into the next lowest age. I'll make sure this is duly mentioned in the roxygen.

**Comment by timriffe** [comment]
haha, `axPAS()` example `NA`s due to inverted rate definition. Changed to `Deaths/Exposures`. Coffee anyone?

**Comment by timriffe** [comment]
`ax.greville.mortpak()` I see what's going on. There are lots of ways to give combos of those 3 vectors, but actually it's always assumed that either `nMx` or `nqx` are present but not both, because if you had both then `nax` falls out by identity. So I'll add that in just in case both mx and qx are given. lx is just a substitute for qx, related by identity. Will get it sorted.

**Comment by timriffe** [comment]
'ax.greville.mortpak()` now very modified. Added `Age` and `AgeInt` args, allowed for any combo of `nMx`, `nqx`/`lx`. Would appreciate testing of this once pushed.

**Comment by timriffe** [comment]
yes, spencer produces `NA`s on end points because it's a moving window. Note that all the `*_smth()` functions also have this (except `arriaga_smth()` and `strong_smth()`, which account for end points. In this way, `spencer()` and `zelnik()` behave as do `kkn_smth()`, `carrier_farrag_smth()` and friends. There is still no next-level wrapper to offer ways to account for endpoints in single-age data, but there are several possibilities that we need to think of, mostly based on grouping to 5 then graduating back to single, with optional in-between 5-yr age group smooth. These are kind of involved solutions though, so I've put it off until I have a clear idea of what to do with single age data. Maybe we call soon and discuss.
