### ISSUE TITLE
LTabr > OAG=TRUE not working properly

### ISSUE THREAD

**Issue by patrick-gerland** [timriffe/DemoTools#83]
If OAG=TRUE and OAnew is not specified, currently the input mx for open age group is not the output mx for the open age group (e.g., 100), and the nAx, nLx, Tx, Ex are incorrect.

Here is an example of the algebra used to get the closing values for the open age group:

ifun <- function(SexCode, AgeGrpStart, AgeGrpSpan, mx) {
	LT <- LTabr(nMx = mx, Age = AgeGrpStart, AgeInt = AgeGrpSpan, radix = 1e+05, axmethod = "UN", Sex = unique(SexCode), region = "W", mod = FALSE, OAG=TRUE)
	
	## deal with open age group
	i <- length(LT$Age)
	LT$nMx[i] <- mx[i]
	LT$nAx[i] <- 1 / mx[i]
	LT$nqx[i] <- NA
	LT$nLx[i] <- LT$nAx[i] * LT$ndx[i]
	LT$Tx[i] <- LT$nLx[i]
	LT$ex[i]  <- 1 / mx[i]

**Comment by timriffe** [comment]
It's common practice to closeout a(omega) and e(omega) with the inverse of m(omega), but we decided to use a hopefully-more-robust closeout method, in part because of this article [https://www.nature.com/articles/palcomms201549.pdf](Missov et al 2016). The procedure is to extrapolate m(x) to a very high age (130), calculate the entire lifetable from this, then truncate the lifetable. Some details:

1. When left blank, `OAnew` defaults to `max(Age)`. A side effect of choosing this method is that in cases where the input data only go up to age (say) 80, choosing different `OAnew` (say 80, 90, 100) will not affect the values of e(80) etc. I've quickly verified that the other columns are coherent with each other as well. But the relationship between M(omega) and a/e(omega) will not hold.

2. We use 1 for q(omega) and not `NA`, standard practice AFAIK and also consistent. If `NA` is really needed at UNPD, then I think this should happen in the `DDSQLtools` wrapper instead.

3. I've corrected M(omega) now in two ways. i) if `OAG` is TRUE and `OAnew == max(Age)` (this was your example case), then the input M(omega) is preserved. In all other cases (`OAG == FALSE`, `OAnew != max(Age)`), then M(omega) is defined at l(omega) / T(omega) (or d(omega) / L(omega)).
